name: dtek

on:
  schedule:
    - cron: "15 * * * *" # at 45 minutes past the hour, every 3 hours, between 05:00 and 23:59
    - cron: "45 5-23/3 * * *" # at 45 minutes past the hour, every 3 hours, between 05:00 and 23:59
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.14"
  PLAYWRIGHT_VERSION: "1.58.0"

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-slim
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: false
    strategy:
      matrix:
        environment: [dtek-oem, dtek-krem]
    environment: ${{ matrix.environment }}
    env:
      OUTPUT_FILE: ${{ vars.NAME }}.json
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v6

      - name: Restore Python cache
        uses: actions/cache@v4
        id: python-cache
        with:
          path: ~/.local/share/virtualenvs
          key: >-
            ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}
          restore-keys: |
            ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}
            ${{ runner.os }}-python-

      - name: Checkout the data branch
        uses: actions/checkout@v6
        with:
          ref: data
          path: data

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          pip-install: playwright==${{ env.PLAYWRIGHT_VERSION }} requests
          cache: pip

      - name: Restore playwright browser cache
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: >-
            ${{ runner.os }}-playwright-chromium-${{ env.PLAYWRIGHT_VERSION }}
          restore-keys: |
            ${{ runner.os }}-playwright-chromium-${{ env.PLAYWRIGHT_VERSION }}
            ${{ runner.os }}-playwright-

      - name: Install playwright chromium
        run: playwright install chromium --with-deps

      - name: Run scraper for ${{ vars.NAME }}
        env:
          SHUTDOWNS_URL: ${{ vars.SHUTDOWNS_URL }}
          BROWSERLESS_TOKEN: ${{ secrets.BROWSERLESS_TOKEN }}
        run: python scrape.py > ${{ github.workspace }}/data/${{ env.OUTPUT_FILE }}

      - name: Detect changes
        id: changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          cd ${{ github.workspace }}/data
          git add ${{ env.OUTPUT_FILE }}
          if git diff --staged --exit-code; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"s
            git commit -m "${{ env.OUTPUT_FILE }}-$(date +%s)"
            git push origin HEAD:data
          fi

      - name: Trigger the webhook
        if:
          steps.changes.outputs.changed == 'true' && env.WEBHOOK_URL != ''
        run: |
          curl -s -d "@${{ github.workspace }}/data/${{ env.OUTPUT_FILE }}" --header "Content-Type: application/json" "${{ env.WEBHOOK_URL }}"
